
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { X, Film, Image as ImageIcon, Loader2, Cloud, Terminal, Link, FileUp, Save, Copy, CheckCircle2, ShieldAlert, Tag, Plus, Trash2, ListFilter, ExternalLink, Sparkles, RefreshCw } from 'lucide-react';
import { Movie, User } from '../types.ts';
import { saveVideoToCloud } from '../services/storageService.ts';

interface UploadModalProps {
  user: User;
  onClose: () => void;
  onUpload: (newMovie: Movie) => void;
  movieToEdit?: Movie | null;
}

const CATEGORY_OPTIONS = [
  'Viral',
  'onlyfans',
  'Insta post',
  'Sci-Fi',
  'Action',
  'Adventure',
  'Comedy',
  'Horror'
];

interface LinkEntry {
  title: string;
  url: string;
}

const UploadModal: React.FC<UploadModalProps> = ({ user, onClose, onUpload, movieToEdit }) => {
  const isEditMode = !!movieToEdit;
  const [uploadType, setUploadType] = useState<'file' | 'link'>(movieToEdit?.videoUrl?.includes('supabase.co') ? 'file' : 'link');
  const [showBulkImport, setShowBulkImport] = useState(false);
  const [bulkText, setBulkText] = useState('');
  
  const [title, setTitle] = useState(movieToEdit?.title || '');
  const [description, setDescription] = useState(movieToEdit?.description || '');
  const [genre, setGenre] = useState(movieToEdit?.genre || 'Viral');
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [thumbnailUrl, setThumbnailUrl] = useState(movieToEdit?.thumbnail || '');
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false);
  const [wasAutoGenerated, setWasAutoGenerated] = useState(false);
  
  const [linkEntries, setLinkEntries] = useState<LinkEntry[]>([
    { title: movieToEdit?.title || '', url: movieToEdit?.videoUrl || '' }
  ]);

  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const generateThumbnail = useCallback(async (file: File) => {
    if (!file) return;
    setIsGeneratingThumbnail(true);
    setWasAutoGenerated(false);
    
    const video = document.createElement('video');
    const url = URL.createObjectURL(file);
    
    video.src = url;
    video.muted = true;
    video.playsInline = true;
    video.preload = 'auto';
    video.crossOrigin = "anonymous";

    const capture = () => {
      return new Promise<void>((resolve, reject) => {
        video.onloadedmetadata = () => {
          video.currentTime = Math.min(1.5, video.duration / 2);
        };
        
        video.onseeked = () => {
          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          const ctx = canvas.getContext('2d');
          
          if (ctx) {
            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
            canvas.toBlob((blob) => {
              if (blob) {
                const autoFile = new File([blob], 'thumb.jpg', { type: 'image/jpeg' });
                setThumbnailFile(autoFile);
                setThumbnailPreview(URL.createObjectURL(blob));
                setWasAutoGenerated(true);
              }
              resolve();
            }, 'image/jpeg', 0.9);
          } else {
            reject(new Error("Canvas context failed"));
          }
        };

        video.onerror = (e) => reject(e);
        // Timeout safety
        setTimeout(() => reject(new Error("Thumbnail capture timed out")), 5000);
      });
    };

    try {
      await capture();
    } catch (err) {
      console.error("Auto-thumbnail failed:", err);
    } finally {
      setIsGeneratingThumbnail(false);
      URL.revokeObjectURL(url);
    }
  }, []);

  const handleVideoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setVideoFile(file);
      if (!title) {
        setTitle(file.name.replace(/\.[^/.]+$/, "").replace(/[-_]/g, " "));
      }
      generateThumbnail(file);
    }
  };

  const handleThumbnailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setThumbnailFile(file);
      setWasAutoGenerated(false); // User provided manual one
      const reader = new FileReader();
      reader.onloadend = () => setThumbnailPreview(reader.result as string);
      reader.readAsDataURL(file);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isGeneratingThumbnail) return;
    
    setIsUploading(true);
    setError(null);
    setUploadProgress(0);
    
    try {
      if (uploadType === 'file') {
        const metadata: Partial<Movie> = {
          id: movieToEdit?.id,
          title,
          description,
          genre,
          uploaderId: user.id,
          uploaderName: user.name,
          thumbnail: thumbnailUrl || (movieToEdit?.thumbnail || undefined)
        };

        const savedMovie = await saveVideoToCloud(metadata, videoFile, thumbnailFile, setUploadProgress);
        onUpload(savedMovie);
      } else {
        const total = linkEntries.length;
        for (let i = 0; i < total; i++) {
          const entry = linkEntries[i];
          if (!entry.url || !entry.title) continue;

          const metadata: Partial<Movie> = {
            id: i === 0 ? movieToEdit?.id : undefined,
            title: entry.title,
            description,
            genre,
            uploaderId: user.id,
            uploaderName: user.name,
            videoUrl: entry.url,
            thumbnail: thumbnailUrl || (movieToEdit?.thumbnail || undefined)
          };

          const savedMovie = await saveVideoToCloud(
            metadata, 
            null, 
            i === 0 ? thumbnailFile : null,
            (p) => setUploadProgress(Math.round(((i / total) * 100) + (p / total)))
          );
          
          if (i === 0 && savedMovie.thumbnail) setThumbnailUrl(savedMovie.thumbnail);
          onUpload(savedMovie);
        }
      }
      onClose();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsUploading(false);
    }
  };

  const copyToClipboard = (text: string, field: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 3000);
  };

  const handleBulkImport = () => {
    const lines = bulkText.split('\n').filter(line => line.trim());
    const newEntries: LinkEntry[] = lines.map(line => {
      const parts = line.split('|');
      if (parts.length >= 2) return { title: parts[0].trim(), url: parts[1].trim() };
      return { title: `Imported ${Date.now()}`, url: line.trim() };
    });
    if (newEntries.length > 0) {
      setLinkEntries(newEntries);
      setShowBulkImport(false);
      setBulkText('');
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-0 sm:p-4 bg-black/90 backdrop-blur-md overflow-y-auto">
      <div className="bg-[#181818] w-full max-w-xl min-h-screen sm:min-h-0 sm:rounded-3xl overflow-hidden shadow-2xl border border-white/10 animate-in slide-in-from-bottom-4 duration-300">
        
        <div className="p-4 sm:p-6 border-b border-white/10 flex items-center justify-between">
          <h2 className="text-lg sm:text-xl font-black flex items-center text-white uppercase italic tracking-tighter">
            {isEditMode ? <Save className="w-5 h-5 mr-2 text-blue-500" /> : <Cloud className="w-5 h-5 mr-2 text-red-600" />}
            {isEditMode ? 'Edit Broadcast' : 'Upload Content'}
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-red-500 transition p-2">
            <X className="w-6 h-6" />
          </button>
        </div>

        {error && (
          <div className="m-5 p-4 bg-red-500/10 border border-red-500/20 rounded-2xl animate-in shake-in">
            <div className="flex items-start space-x-3 text-red-500">
              <ShieldAlert className="w-6 h-6 shrink-0 mt-0.5" />
              <div className="space-y-1 text-left flex-1">
                <p className="font-black uppercase tracking-widest text-[10px]">Critical Error</p>
                <p className="text-xs opacity-90 leading-relaxed font-bold">{error}</p>
              </div>
            </div>
            <button onClick={() => copyToClipboard(error, 'err')} className="mt-2 text-[8px] font-black uppercase text-gray-400 hover:text-white flex items-center">
              <Copy className="w-2.5 h-2.5 mr-1" /> Copy Error Log
            </button>
          </div>
        )}

        {!isEditMode && (
          <div className="flex bg-black/40 p-1 mx-5 mt-5 sm:mx-8 rounded-xl border border-white/5">
             <button onClick={() => setUploadType('file')} className={`flex-1 flex items-center justify-center space-x-2 py-2 rounded-lg text-xs font-black uppercase tracking-widest transition-all ${uploadType === 'file' ? 'bg-red-600 text-white shadow-lg' : 'text-gray-500'}`}>
               <FileUp className="w-4 h-4" /> <span>Local File</span>
             </button>
             <button onClick={() => setUploadType('link')} className={`flex-1 flex items-center justify-center space-x-2 py-2 rounded-lg text-xs font-black uppercase tracking-widest transition-all ${uploadType === 'link' ? 'bg-red-600 text-white shadow-lg' : 'text-gray-500'}`}>
               <Link className="w-4 h-4" /> <span>Network Link</span>
             </button>
          </div>
        )}

        <form onSubmit={handleSubmit} className="p-5 sm:p-8 space-y-5">
          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {uploadType === 'file' && (
                <div className="col-span-full md:col-span-1">
                  <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-1.5">Broadcast Title</label>
                  <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} className="w-full bg-[#252525] border border-white/5 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-red-600 outline-none font-bold text-sm" placeholder="e.g. Action Highlights" required={uploadType === 'file'} />
                </div>
              )}
              <div className={uploadType === 'link' ? 'col-span-full' : 'col-span-full md:col-span-1'}>
                <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-1.5">Category</label>
                <select value={genre} onChange={(e) => setGenre(e.target.value)} className="w-full bg-[#252525] border border-white/5 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-red-600 outline-none font-bold text-sm appearance-none cursor-pointer">
                  {CATEGORY_OPTIONS.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                </select>
              </div>
            </div>

            {uploadType === 'link' && (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Target URLs</label>
                  <div className="flex space-x-3">
                    <button type="button" onClick={() => setShowBulkImport(!showBulkImport)} className="text-[9px] font-black text-blue-500 uppercase tracking-widest hover:underline">Bulk</button>
                    <button type="button" onClick={() => setLinkEntries([...linkEntries, { title: '', url: '' }])} className="text-[9px] font-black text-red-500 uppercase tracking-widest hover:underline">+ Add</button>
                  </div>
                </div>
                {showBulkImport && (
                  <textarea value={bulkText} onChange={(e) => setBulkText(e.target.value)} className="w-full bg-black/40 border border-white/5 rounded-xl p-3 text-xs font-mono min-h-[100px] outline-none" placeholder="Title | URL" />
                )}
                {linkEntries.map((e, i) => (
                  <div key={i} className="flex space-x-2 bg-black/20 p-2 rounded-xl border border-white/5">
                    <input value={e.title} onChange={(ev) => { const n = [...linkEntries]; n[i].title = ev.target.value; setLinkEntries(n); }} className="flex-1 bg-transparent text-xs font-bold outline-none" placeholder="Title" required />
                    <input value={e.url} onChange={(ev) => { const n = [...linkEntries]; n[i].url = ev.target.value; setLinkEntries(n); }} className="flex-1 bg-transparent text-xs font-bold outline-none" placeholder="URL" required />
                    {linkEntries.length > 1 && <button onClick={() => setLinkEntries(linkEntries.filter((_, idx) => idx !== i))} type="button" className="text-gray-600 hover:text-red-500"><Trash2 className="w-4 h-4" /></button>}
                  </div>
                ))}
              </div>
            )}

            <div className="grid grid-cols-2 gap-4">
              {uploadType === 'file' && (
                <label className="flex flex-col items-center justify-center border-2 border-dashed border-white/5 rounded-2xl p-4 cursor-pointer hover:border-red-600/50 hover:bg-white/5 transition h-32 group">
                  <Film className={`w-8 h-8 ${videoFile ? 'text-green-500' : 'text-gray-600 group-hover:text-red-500'}`} />
                  <span className="text-[10px] mt-2 font-black uppercase text-gray-500 truncate w-full text-center px-2">
                    {videoFile ? videoFile.name : 'Choose Video'}
                  </span>
                  <input type="file" accept="video/*" className="hidden" onChange={handleVideoChange} />
                </label>
              )}

              <label className={`relative flex flex-col items-center justify-center border-2 border-dashed border-white/5 rounded-2xl p-4 cursor-pointer hover:border-red-600/50 hover:bg-white/5 transition h-32 overflow-hidden ${uploadType === 'link' ? 'col-span-full' : ''}`}>
                {thumbnailPreview || thumbnailUrl ? (
                  <img src={thumbnailPreview || thumbnailUrl} className="absolute inset-0 w-full h-full object-cover opacity-60" />
                ) : <ImageIcon className="w-8 h-8 text-gray-600" />}

                {isGeneratingThumbnail ? (
                   <div className="relative z-10 flex flex-col items-center">
                     <Loader2 className="w-6 h-6 animate-spin text-red-600" />
                     <span className="text-[9px] font-black text-white mt-1 uppercase">Framing...</span>
                   </div>
                ) : (
                  <div className="relative z-10 flex flex-col items-center">
                    <span className="text-[9px] font-black uppercase text-white bg-black/60 px-3 py-1 rounded-full border border-white/10 backdrop-blur-sm flex items-center">
                      {wasAutoGenerated ? 'Auto Frame' : 'Custom Cover'}
                      {wasAutoGenerated && <Sparkles className="w-2.5 h-2.5 ml-1 text-yellow-400" />}
                    </span>
                    {videoFile && !isGeneratingThumbnail && (
                      <button onClick={(e) => { e.preventDefault(); generateThumbnail(videoFile); }} className="mt-2 text-[8px] font-black uppercase text-red-500 bg-black/40 px-2 py-1 rounded border border-red-500/20">Re-Capture</button>
                    )}
                  </div>
                )}
                <input type="file" accept="image/*" className="hidden" onChange={handleThumbnailChange} />
              </label>
            </div>
          </div>

          {isUploading && (
            <div className="space-y-2 pt-4">
              <div className="flex justify-between text-[10px] font-black text-red-500 uppercase tracking-widest">
                <span>Transmitting</span> <span>{uploadProgress}%</span>
              </div>
              <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                <div className="h-full bg-red-600 transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
              </div>
            </div>
          )}

          <button 
            type="submit" 
            disabled={isUploading || isGeneratingThumbnail}
            className="w-full bg-red-600 hover:bg-red-700 disabled:opacity-50 text-white font-black py-4 rounded-2xl transition flex items-center justify-center uppercase tracking-[0.2em] text-xs shadow-xl active:scale-95"
          >
            {isUploading ? <Loader2 className="w-5 h-5 animate-spin" /> : (isEditMode ? 'Update Broadcast' : 'Publish to Stream')}
          </button>
        </form>
      </div>
    </div>
  );
};

export default UploadModal;
