// @ts-nocheck
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { X, Film, Image as ImageIcon, Loader2, Cloud, Terminal, Link, FileUp, Save, Copy, CheckCircle2, ShieldAlert, Tag, Plus, Trash2, ListFilter, ExternalLink, Sparkles, RefreshCw } from 'lucide-react';
import { Movie, User } from '../types.ts';
import { saveVideoToCloud } from '../services/storageService.ts';

interface UploadModalProps {
  user: User;
  onClose: () => void;
  onUpload: (newMovie: Movie) => void;
  movieToEdit?: Movie | null;
}

const CATEGORY_OPTIONS = [
  'Viral',
  'onlyfans',
  'Insta post',
  'Sci-Fi',
  'Action',
  'Adventure',
  'Comedy',
  'Horror'
];

interface LinkEntry {
  title: string;
  url: string;
}

const UploadModal: React.FC<UploadModalProps> = ({ user, onClose, onUpload, movieToEdit }) => {
  const isEditMode = !!movieToEdit;
  const [uploadType, setUploadType] = useState<'file' | 'link'>(movieToEdit?.videoUrl?.includes('supabase.co') ? 'file' : 'link');
  
  const [title, setTitle] = useState(movieToEdit?.title || '');
  const [description, setDescription] = useState(movieToEdit?.description || '');
  const [genre, setGenre] = useState(movieToEdit?.genre || 'Viral');
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [thumbnailUrl, setThumbnailUrl] = useState(movieToEdit?.thumbnail || '');
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false);
  const [wasAutoGenerated, setWasAutoGenerated] = useState(false);
  
  const [linkEntries, setLinkEntries] = useState<LinkEntry[]>([
    { title: movieToEdit?.title || '', url: movieToEdit?.videoUrl || '' }
  ]);

  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  // Strictly generates a thumbnail from the FIRST frame of the video
  const generateThumbnail = useCallback(async (file: File) => {
    if (!file) return;
    setIsGeneratingThumbnail(true);
    setWasAutoGenerated(false);
    
    const video = document.createElement('video');
    const url = URL.createObjectURL(file);
    
    video.src = url;
    video.muted = true;
    video.playsInline = true;
    video.preload = 'auto';
    video.crossOrigin = "anonymous"; 

    const capture = () => {
      return new Promise<void>((resolve, reject) => {
        // Set to 0 to strictly get the first frame
        video.onloadedmetadata = () => {
          video.currentTime = 0;
        };
        
        video.onseeked = () => {
          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          const ctx = canvas.getContext('2d');
          
          if (ctx && canvas.width > 0 && canvas.height > 0) {
            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
            canvas.toBlob((blob) => {
              if (blob) {
                const generatedFile = new File([blob], 'first-frame.jpg', { type: 'image/jpeg' });
                setThumbnailFile(generatedFile);
                setThumbnailPreview(URL.createObjectURL(blob));
                setWasAutoGenerated(true);
              }
              setIsGeneratingThumbnail(false);
              resolve();
            }, 'image/jpeg', 0.85);
          } else {
            setIsGeneratingThumbnail(false);
            reject(new Error('Canvas capture failed - invalid dimensions'));
          }
        };

        video.onerror = () => {
          setIsGeneratingThumbnail(false);
          reject(new Error('Video stream could not be loaded for framing'));
        };

        // Safety timeout
        setTimeout(() => {
          if (isGeneratingThumbnail) {
            setIsGeneratingThumbnail(false);
            reject(new Error('Thumbnail capture timed out'));
          }
        }, 8000);
      });
    };

    capture().catch(err => {
      console.error("Auto-thumbnail capture failed:", err);
      setIsGeneratingThumbnail(false);
    });
  }, []);

  const handleUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isGeneratingThumbnail) return;
    
    setIsUploading(true);
    setError(null);

    try {
      const movieData: Partial<Movie> = {
        id: movieToEdit?.id,
        title,
        description,
        genre,
        uploaderId: user.id,
        uploaderName: user.name,
        videoUrl: uploadType === 'link' ? linkEntries[0].url : undefined,
        thumbnail: thumbnailUrl, // Existing URL if editing
        year: movieToEdit?.year || new Date().getFullYear(),
        rating: movieToEdit?.rating || 'NR'
      };

      // saveVideoToCloud handles uploading thumbnailFile if it exists
      const result = await saveVideoToCloud(
        movieData,
        uploadType === 'file' ? videoFile : null,
        thumbnailFile,
        (progress) => setUploadProgress(progress)
      );

      onUpload(result);
      onClose();
    } catch (err: any) {
      setError(err.message || 'Transmission failed. Ensure your connection is stable.');
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-0 md:p-6 bg-black/95 backdrop-blur-xl overflow-y-auto">
      <div className="relative bg-[#121212] w-full max-w-4xl min-h-screen md:min-h-0 md:rounded-[2.5rem] overflow-hidden shadow-[0_0_100px_rgba(229,9,20,0.2)] border border-white/5 animate-in fade-in zoom-in-95 duration-300">
        
        {/* Header */}
        <div className="p-6 md:p-10 border-b border-white/5 flex items-center justify-between bg-gradient-to-r from-red-600/5 to-transparent">
          <div className="flex items-center space-x-4">
            <div className="bg-red-600 p-3 rounded-2xl shadow-lg shadow-red-600/20">
              {isEditMode ? <RefreshCw className="w-6 h-6 text-white" /> : <FileUp className="w-6 h-6 text-white" />}
            </div>
            <div>
              <h2 className="text-xl md:text-3xl font-black text-white uppercase italic tracking-tighter">
                {isEditMode ? 'Edit Broadcast' : 'Deploy New Signal'}
              </h2>
              <p className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.3em]">Broadcast ID: {movieToEdit?.id || 'pending'}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-3 hover:bg-white/5 rounded-full transition-all active:scale-90 border border-white/5">
            <X className="w-6 h-6 text-gray-400" />
          </button>
        </div>

        <form onSubmit={handleUpload} className="p-6 md:p-10 space-y-8">
          {error && (
            <div className="bg-red-500/10 border border-red-500/20 p-5 rounded-2xl text-red-500 text-xs font-black uppercase tracking-widest flex items-center animate-in slide-in-from-top-2">
              <ShieldAlert className="w-5 h-5 mr-3 shrink-0" />
              {error}
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
            {/* Left Column: Metadata */}
            <div className="lg:col-span-7 space-y-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Broadcast Title</label>
                <div className="relative group">
                  <Terminal className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-red-600 opacity-50 group-focus-within:opacity-100 transition-opacity" />
                  <input 
                    type="text" 
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="w-full bg-white/5 border border-white/10 rounded-2xl pl-12 pr-4 py-4 outline-none focus:border-red-600/50 focus:ring-4 focus:ring-red-600/10 transition text-sm font-bold"
                    placeholder="SIGNAL_NAME_HERE"
                    required
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Category</label>
                  <div className="relative">
                    <Tag className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
                    <select 
                      value={genre}
                      onChange={(e) => setGenre(e.target.value)}
                      className="w-full bg-[#181818] border border-white/10 rounded-2xl pl-12 pr-4 py-4 outline-none focus:border-red-600/50 transition text-sm font-bold appearance-none cursor-pointer"
                    >
                      {CATEGORY_OPTIONS.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                    </select>
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Uploader</label>
                  <div className="w-full bg-white/5 border border-white/10 rounded-2xl px-4 py-4 text-sm font-bold text-gray-400 flex items-center">
                    <img src={user.avatar} className="w-5 h-5 rounded-full mr-2 grayscale" alt="" />
                    {user.name}
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Data Description</label>
                <textarea 
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-4 outline-none focus:border-red-600/50 transition h-40 resize-none text-sm font-medium leading-relaxed"
                  placeholder="Encoded transmission details..."
                />
              </div>
            </div>

            {/* Right Column: Assets */}
            <div className="lg:col-span-5 space-y-6">
              <div className="flex bg-white/5 p-1.5 rounded-2xl border border-white/10">
                <button 
                  type="button"
                  onClick={() => setUploadType('file')}
                  className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${uploadType === 'file' ? 'bg-red-600 text-white shadow-lg' : 'text-gray-500 hover:text-white'}`}
                >
                  <FileUp className="w-3.5 h-3.5 mx-auto mb-1" />
                  Local File
                </button>
                <button 
                  type="button"
                  onClick={() => setUploadType('link')}
                  className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${uploadType === 'link' ? 'bg-red-600 text-white shadow-lg' : 'text-gray-500 hover:text-white'}`}
                >
                  <Link className="w-3.5 h-3.5 mx-auto mb-1" />
                  Direct Link
                </button>
              </div>

              {uploadType === 'file' ? (
                <div className="relative aspect-video rounded-3xl border-2 border-dashed border-white/10 flex flex-col items-center justify-center p-6 text-center hover:border-red-600/40 transition group cursor-pointer bg-white/[0.02]">
                  <input 
                    type="file" 
                    accept="video/*"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) {
                        setVideoFile(file);
                        generateThumbnail(file);
                      }
                    }}
                    className="absolute inset-0 opacity-0 cursor-pointer z-10"
                  />
                  <Cloud className={`w-12 h-12 mb-4 transition-transform duration-500 ${videoFile ? 'text-green-500 scale-110' : 'text-gray-600 group-hover:scale-110 group-hover:text-red-600'}`} />
                  <p className="text-xs font-black uppercase tracking-widest text-white truncate max-w-full px-4">
                    {videoFile ? videoFile.name : 'Select Transcoding Unit'}
                  </p>
                  <p className="text-[9px] text-gray-500 font-bold mt-2 uppercase">MP4 / MOV / WEBM (MAX 1GB)</p>
                </div>
              ) : (
                <div className="space-y-2">
                   <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Video Endpoint URL</label>
                   <input 
                    type="url" 
                    value={linkEntries[0].url}
                    onChange={(e) => setLinkEntries([{ ...linkEntries[0], url: e.target.value }])}
                    className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-4 outline-none focus:border-red-600/50 transition text-sm font-mono text-red-500"
                    placeholder="https://content.delivery/video.mp4"
                    required={uploadType === 'link'}
                  />
                </div>
              )}

              <div className="space-y-4">
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em] ml-1">Signal Cover (Thumbnail)</label>
                <div className="relative aspect-video rounded-3xl overflow-hidden bg-zinc-900 border border-white/5 group shadow-2xl">
                  {(thumbnailPreview || thumbnailUrl) ? (
                    <img src={thumbnailPreview || thumbnailUrl} alt="Signal Preview" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" />
                  ) : (
                    <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-700">
                      <ImageIcon className="w-10 h-10 mb-2 opacity-20" />
                      <span className="text-[10px] font-black uppercase tracking-[0.3em]">No Visual Signal</span>
                    </div>
                  )}
                  
                  <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-all duration-300 flex items-center justify-center backdrop-blur-sm">
                    <input 
                      type="file" 
                      accept="image/*"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) {
                          setThumbnailFile(file);
                          setThumbnailPreview(URL.createObjectURL(file));
                          setWasAutoGenerated(false);
                        }
                      }}
                      className="absolute inset-0 opacity-0 cursor-pointer z-10"
                    />
                    <div className="bg-white text-black px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl transform translate-y-4 group-hover:translate-y-0 transition-transform">
                      Manual Override
                    </div>
                  </div>

                  {isGeneratingThumbnail && (
                    <div className="absolute inset-0 bg-black/90 flex flex-col items-center justify-center z-20">
                      <Loader2 className="w-10 h-10 text-red-600 animate-spin mb-4" />
                      <span className="text-[10px] font-black text-white uppercase tracking-[0.5em] animate-pulse">Capturing First Frame...</span>
                    </div>
                  )}
                </div>
                {wasAutoGenerated && (
                  <div className="flex items-center space-x-2 text-green-500 bg-green-500/10 w-fit px-4 py-2 rounded-full border border-green-500/20">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span className="text-[9px] font-black uppercase tracking-widest">Extracted First Frame</span>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Footer Actions */}
          <div className="pt-10 border-t border-white/5 flex flex-col space-y-6">
             {isUploading && (
               <div className="w-full space-y-3 animate-in fade-in slide-in-from-bottom-2">
                  <div className="flex justify-between items-end">
                    <div className="space-y-1">
                      <span className="text-[10px] font-black uppercase tracking-[0.4em] text-red-600">Uploading Signal</span>
                      <p className="text-[9px] text-gray-500 font-bold uppercase">Broadcasting packets to cloud relays...</p>
                    </div>
                    <span className="text-2xl font-black italic text-white">{uploadProgress}%</span>
                  </div>
                  <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden border border-white/5">
                    <div className="h-full bg-gradient-to-r from-red-600 to-red-400 transition-all duration-300 shadow-[0_0_15px_rgba(229,9,20,0.4)]" style={{ width: `${uploadProgress}%` }} />
                  </div>
               </div>
             )}
             
             <div className="flex flex-col sm:flex-row space-y-3 sm:space-y-0 sm:space-x-4">
                <button 
                  type="button" 
                  onClick={onClose}
                  disabled={isUploading}
                  className="flex-1 py-5 rounded-[1.5rem] text-[10px] font-black uppercase tracking-[0.4em] text-gray-500 hover:text-white hover:bg-white/5 border border-transparent hover:border-white/10 transition-all active:scale-95 disabled:opacity-30"
                >
                  Abort Mission
                </button>
                <button 
                  type="submit"
                  disabled={isUploading || isGeneratingThumbnail || (uploadType === 'file' && !videoFile && !isEditMode)}
                  className="flex-[2] relative overflow-hidden group/btn bg-red-600 hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed text-white py-5 rounded-[1.5rem] text-[10px] font-black uppercase tracking-[0.4em] transition-all shadow-[0_20px_40px_rgba(229,9,20,0.3)] active:scale-[0.98]"
                >
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover/btn:animate-[shimmer_2s_infinite] pointer-events-none" />
                  {isUploading ? (
                    <div className="flex items-center justify-center">
                      <Loader2 className="w-5 h-5 animate-spin mr-3" />
                      <span>Transmitting...</span>
                    </div>
                  ) : (
                    <div className="flex items-center justify-center">
                      {isEditMode ? <Save className="w-5 h-5 mr-3" /> : <Plus className="w-5 h-5 mr-3" />}
                      <span>{isEditMode ? 'Commit Changes' : 'Initialize Broadcast'}</span>
                    </div>
                  )}
                </button>
             </div>
          </div>
        </form>
      </div>
      <style>{`
        @keyframes shimmer {
          100% { transform: translateX(100%); }
        }
      `}</style>
    </div>
  );
};

export default UploadModal;
